package sv.edu.udb.www.Cuponera.Entities;
// Generated 11-17-2018 03:23:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Pattern;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="Cuponera"
    , uniqueConstraints = @UniqueConstraint(columnNames="dui") 
)
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     @NotBlank(message="El nombre es obligatorio")
     private String nombre;
     @NotBlank(message="El apellido es obligatorio")
     private String apellido;
     @Pattern(regexp="[267][0-9]{3}-[0-9]{4}", message="Formato de telefono incorrecto (####-####)")
     @NotBlank(message="El telefono es obligatorio")
     private String telefono;
     @NotBlank(message="La dirección es obligatoria")
     private String direccion;
     @Pattern(regexp="[0-9]{8}-[0-9]", message="Formato de DUI incorrecto (########-#)")
     @NotBlank(message="El DUI es obligatorio")
     private String dui;
     private String tarjeta;
     private String pin;
     private String correo;
     private String clave;
     private String confirmacion;
     private Set<Cupon> cupons = new HashSet<Cupon>(0);

    public Cliente() {
    }

	
    public Cliente(Usuario usuario, String nombre, String apellido, String telefono, String direccion, String dui, String tarjeta, String pin) {
        this.usuario = usuario;
        this.nombre = nombre;
        this.apellido = apellido;
        this.telefono = telefono;
        this.direccion = direccion;
        this.dui = dui;
        this.tarjeta = tarjeta;
        this.pin = pin;
    }
    public Cliente(Usuario usuario, String nombre, String apellido, String telefono, String direccion, String dui, String tarjeta, String pin, Set<Cupon> cupons) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.direccion = direccion;
       this.dui = dui;
       this.tarjeta = tarjeta;
       this.pin = pin;
       this.cupons = cupons;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombre", nullable=false, length=150)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=150)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="telefono", nullable=false, length=9)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="direccion", nullable=false, length=150)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="dui", unique=true, nullable=false, length=10)
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }

    
    @Column(name="tarjeta", nullable=true, length=64)
    public String getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(String tarjeta) {
        this.tarjeta = tarjeta;
    }

    
    @Column(name="pin", nullable=true, length=64)
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Cupon> getCupons() {
        return this.cupons;
    }
    
    public void setCupons(Set<Cupon> cupons) {
        this.cupons = cupons;
    }


    @Transient
    public String getCorreo() {
		return correo;
	}


	public void setCorreo(String correo) {
		this.correo = correo;
	}


	@Transient
    public String getClave() {
		return clave;
	}


	public void setClave(String clave) {
		this.clave = clave;
	}


	@Transient
    public String getConfirmacion() {
		return confirmacion;
	}


	public void setConfirmacion(String confirmacion) {
		this.confirmacion = confirmacion;
	}




}


