package sv.edu.udb.www.Cuponera.Entities;
// Generated 11-17-2018 03:23:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cupon generated by hbm2java
 */
@Entity
@Table(name="cupon"
    ,catalog="Cuponera"
)
public class Cupon  implements java.io.Serializable {


     private String id;
     private Cliente cliente;
     private EstadoCupon estadoCupon;
     private Promocion promocion;
     private Date fechaCompra;
     private Date fechaCanje;

    public Cupon() {
    }

    public Cupon(String id, Cliente cliente, EstadoCupon estadoCupon, Promocion promocion, Date fechaCompra, Date fechaCanje) {
       this.id = id;
       this.cliente = cliente;
       this.estadoCupon = estadoCupon;
       this.promocion = promocion;
       this.fechaCompra = fechaCompra;
       this.fechaCanje = fechaCanje;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=13)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_estado", nullable=false)
    public EstadoCupon getEstadoCupon() {
        return this.estadoCupon;
    }
    
    public void setEstadoCupon(EstadoCupon estadoCupon) {
        this.estadoCupon = estadoCupon;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_promocion", nullable=false)
    public Promocion getPromocion() {
        return this.promocion;
    }
    
    public void setPromocion(Promocion promocion) {
        this.promocion = promocion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_compra", nullable=false, length=10)
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_canje", nullable=false, length=10)
    public Date getFechaCanje() {
        return this.fechaCanje;
    }
    
    public void setFechaCanje(Date fechaCanje) {
        this.fechaCanje = fechaCanje;
    }




}


