package sv.edu.udb.www.Cuponera.Entities;
// Generated 11-17-2018 03:23:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="empresa"
    ,catalog="Cuponera"
    , uniqueConstraints = @UniqueConstraint(columnNames="identificador") 
)
public class Empresa  implements java.io.Serializable {


     private Integer id;
     private Rubro rubro;
     private String identificador;
     private String nombre;
     private String direccion;
     private String nombreContacto;
     private String telefono;
     private long comision;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);
     private Set<Promocion> promocions = new HashSet<Promocion>(0);

    public Empresa() {
    }

	
    public Empresa(Rubro rubro, String identificador, String nombre, String direccion, String nombreContacto, String telefono, long comision) {
        this.rubro = rubro;
        this.identificador = identificador;
        this.nombre = nombre;
        this.direccion = direccion;
        this.nombreContacto = nombreContacto;
        this.telefono = telefono;
        this.comision = comision;
    }
    public Empresa(Rubro rubro, String identificador, String nombre, String direccion, String nombreContacto, String telefono, long comision, Set<Empleado> empleados, Set<Promocion> promocions) {
       this.rubro = rubro;
       this.identificador = identificador;
       this.nombre = nombre;
       this.direccion = direccion;
       this.nombreContacto = nombreContacto;
       this.telefono = telefono;
       this.comision = comision;
       this.empleados = empleados;
       this.promocions = promocions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rubro", nullable=false)
    public Rubro getRubro() {
        return this.rubro;
    }
    
    public void setRubro(Rubro rubro) {
        this.rubro = rubro;
    }

    
    @Column(name="identificador", unique=true, nullable=false, length=6)
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }

    
    @Column(name="nombre", nullable=false, length=150)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="direccion", nullable=false, length=150)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="nombre_contacto", nullable=false, length=150)
    public String getNombreContacto() {
        return this.nombreContacto;
    }
    
    public void setNombreContacto(String nombreContacto) {
        this.nombreContacto = nombreContacto;
    }

    
    @Column(name="telefono", nullable=false, length=9)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="comision", nullable=false, precision=10, scale=0)
    public long getComision() {
        return this.comision;
    }
    
    public void setComision(long comision) {
        this.comision = comision;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set<Promocion> getPromocions() {
        return this.promocions;
    }
    
    public void setPromocions(Set<Promocion> promocions) {
        this.promocions = promocions;
    }




}


