package sv.edu.udb.www.Cuponera.Entities;
// Generated 11-17-2018 03:23:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotBlank;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.multipart.MultipartFile;

/**
 * Promocion generated by hbm2java
 */
@Entity
@Table(name="promocion"
    ,catalog="Cuponera"
)
public class Promocion  implements java.io.Serializable {


     private Integer id;
     private Empresa empresa;
     private EstadoOferta estadoOferta;
     @NotBlank(message="El titulo de la oferta es obligatorio")
     private String titulo;
     private long precioRegular;
     private long precioOferta;
     private int cuponesDisponibles;
     @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date fechaInicio;
     @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date fechaFin;
     @DateTimeFormat(pattern = "yyyy-MM-dd")
     private Date fechaLimite;
     @NotBlank(message="La descripcion es obligatoria")
     private String descripcion;
     private String img;
     private MultipartFile fileData;
     private String disponibles;
     private Set<Cupon> cupons = new HashSet<Cupon>(0);

    public Promocion() {
    }

	
    public Promocion(Empresa empresa, EstadoOferta estadoOferta, String titulo, long precioRegular, long precioOferta, int cuponesDisponibles, Date fechaInicio, Date fechaFin, Date fechaLimite, String descripcion, String img) {
        this.empresa = empresa;
        this.estadoOferta = estadoOferta;
        this.titulo = titulo;
        this.precioRegular = precioRegular;
        this.precioOferta = precioOferta;
        this.cuponesDisponibles = cuponesDisponibles;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.fechaLimite = fechaLimite;
        this.descripcion = descripcion;
        this.img = img;
    }
    public Promocion(Empresa empresa, EstadoOferta estadoOferta, String titulo, long precioRegular, long precioOferta, int cuponesDisponibles, Date fechaInicio, Date fechaFin, Date fechaLimite, String descripcion, String img, Set<Cupon> cupons) {
       this.empresa = empresa;
       this.estadoOferta = estadoOferta;
       this.titulo = titulo;
       this.precioRegular = precioRegular;
       this.precioOferta = precioOferta;
       this.cuponesDisponibles = cuponesDisponibles;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.fechaLimite = fechaLimite;
       this.descripcion = descripcion;
       this.img = img;
       this.cupons = cupons;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_empresa", nullable=false)
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_estado", nullable=false)
    public EstadoOferta getEstadoOferta() {
        return this.estadoOferta;
    }
    
    public void setEstadoOferta(EstadoOferta estadoOferta) {
        this.estadoOferta = estadoOferta;
    }

    
    @Column(name="titulo", nullable=false, length=150)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="precio_regular", nullable=false, precision=10, scale=2)
    public long getPrecioRegular() {
        return this.precioRegular;
    }
    
    public void setPrecioRegular(long precioRegular) {
        this.precioRegular = precioRegular;
    }

    
    @Column(name="precio_oferta", nullable=false, precision=10, scale=2)
    public long getPrecioOferta() {
        return this.precioOferta;
    }
    
    public void setPrecioOferta(long precioOferta) {
        this.precioOferta = precioOferta;
    }

    
    @Column(name="cupones_disponibles", nullable=false)
    public int getCuponesDisponibles() {
        return this.cuponesDisponibles;
    }
    
    public void setCuponesDisponibles(int cuponesDisponibles) {
        this.cuponesDisponibles = cuponesDisponibles;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", nullable=false, length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", nullable=false, length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_limite", nullable=false, length=10)
    public Date getFechaLimite() {
        return this.fechaLimite;
    }
    
    public void setFechaLimite(Date fechaLimite) {
        this.fechaLimite = fechaLimite;
    }

    
    @Column(name="descripcion", nullable=false, length=500)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="img", nullable=false, length=65535)
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="promocion")
    public Set<Cupon> getCupons() {
        return this.cupons;
    }
    
    public void setCupons(Set<Cupon> cupons) {
        this.cupons = cupons;
    }

    @Transient
	public MultipartFile getFileData() {
		return fileData;
	}


	public void setFileData(MultipartFile fileData) {
		this.fileData = fileData;
	}


	@Transient
	public String getDisponibles() {
		return disponibles;
	}


	public void setDisponibles(String disponibles) {
		this.disponibles = disponibles;
	}




}


